#!/usr/bin/env python3
import os
import colors as c
omit=[__file__[2:],'colors.py']
print("Omitting "+', '.join(omit))
for repo in os.listdir('.'):
    if repo not in omit:
        print(c.rc())
        os.system('cd '+repo+' && pwd && save')
print(c.x)
