#!/usr/bin/env python3
import os
import colors as c
omit=[]
repos=[]
for thing in os.listdir('.'):
    if os.path.isdir(thing):
        if '.git' in os.listdir(thing):
            repos.append(thing)
        else:
            omit.append(thing)
    else:
        omit.append(thing)

if omit:
    print("Omitting "+', '.join(omit))
for repo in repos:
    os.system('cd '+repo+' && pwd')
    print(c.rc())
    os.system('cd '+repo+' && save')
    print(c.rc())
print(c.x)
