#!/usr/bin/env python3
import os
import colors as c
omit=[]
repos=[]
defer=[]
def search(folder):
    for thing in os.listdir(folder):
        if os.path.isdir(thing) and thing[0]!='.':
            if '.git' in os.listdir(thing):
                repos.append(thing)
            else:
                defer.append(thing)
        else:
            omit.append(thing)
search(os.environ['HOME'])
for folder in defer:
    search(folder)

print("Deferring "+', '.join(defer))
print("Omitting "+', '.join(omit))
for repo in repos:
    os.system('cd '+repo+' && pwd')
    print(c.rc())
    os.system('cd '+repo+' && save')
    print(c.x)
